services:
  backend:
    image: ${DOCKER_IMAGE_BACKEND}
    container_name: codex_dlc_company-backend
    env_file: .env
    volumes:
      - staticfiles:/app/staticfiles
      - logs:/app/data/logs
    expose:
      - "8000"
    restart: always
    networks:
      - codex_dlc_company-network

  bot:
    image: ${DOCKER_IMAGE_BOT}
    container_name: codex_dlc_company-bot
    env_file: .env
    restart: always
    depends_on:
      - redis
    networks:
      - codex_dlc_company-network

  worker:
    image: ${DOCKER_IMAGE_WORKER}
    container_name: codex_dlc_company-worker
    env_file: .env
    restart: always
    depends_on:
      - redis
    networks:
      - codex_dlc_company-network

  redis:
    image: redis:7-alpine
    container_name: codex_dlc_company-redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    networks:
      - codex_dlc_company-network

  nginx:
    image: ${DOCKER_IMAGE_NGINX}
    container_name: codex_dlc_company-nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./nginx/nginx-main.conf:/etc/nginx/nginx.conf:ro
      - uploads:/app/media:ro
      - certs_volume:/etc/letsencrypt:ro
      - certbot_challenge_volume:/var/www/certbot:ro
    depends_on:
      - backend
    restart: always
    networks:
      - codex_dlc_company-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  certbot:
    image: certbot/certbot:v2.11.0
    container_name: codex_dlc_company-certbot
    volumes:
      - certs_volume:/etc/letsencrypt
      - certbot_challenge_volume:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait ${{!}}; done;'"
    networks:
      - codex_dlc_company-network

volumes:
  staticfiles:
    driver: local
  logs:
    driver: local
  redis-data:
    driver: local
  certs_volume:
    driver: local
  certbot_challenge_volume:
    driver: local

networks:
  codex_dlc_company-network:
    driver: bridge
